-- Your SQL goes here
CREATE TABLE logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name VARCHAR NOT NULL DEFAULT "",
    desc TEXT NOT NULL DEFAULT "",
    time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE attrs (
    attr_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    id INTEGER NOT NULL,
    key VARCHAR NOT NULL,
    val VARCHAR NOT NULL DEFAULT "",
    UNIQUE(id, key) ON CONFLICT REPLACE
);
